import csv

with open("kugosana.csv",encoding="utf-8") as file:
    csv = csv.reader(file)
    saraksts = list(csv)

print()
print("-------------------------------------------------------------------------------------")
print()
print("Faila nosaukums:",file.name)
print()
print("-------------------------------------------------------------------------------------")
print()
print(saraksts)
print()
print("-------------------------------------------------------------------------------------")
print()
print("Ierakstu skaits: ",len(saraksts))
print()
print("-------------------------------------------------------------------------------------")
print()
print("Pirmais ieraksts: ", saraksts[1])
print()
print("-------------------------------------------------------------------------------------")
print()
print("Pēdējais ieraksts: ", saraksts[-1])
print()
print("-------------------------------------------------------------------------------------")
print()
print("Pēdējais ieraksts: ", saraksts[-3])
print()
print("-------------------------------------------------------------------------------------")
print()
print("Pirmie pieci ieraksti: ", saraksts[1:6])